TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += lakeshore625.db
DATA += lakeshore625.proto

#=======================================
include $(TOP)/configure/RULES
